chartName: loggingstack
tolerations:
    effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot


persistentVolumeClaims:
  name: logs-nfs
  accessMode: ReadWriteMany
  storageSize: 10Gi



priorityClass:
  name: infra-critical-daemonset
  value: 1500
storageClassName: ccazfile

loggingStack:
  wettySsh:
    name: wetty-ssh
    image: 313496281593.dkr.ecr.us-east-1.amazonaws.com/wetty-ssh-host:30a4b00-16
  fluentd:
    name: fluentd
    image:
      repository: 313496281593.dkr.ecr.us-east-1.amazonaws.com/fluentd-efs:new


wetty:
    name: wetty
    replicaCount: 1
    image:
      repository: "313496281593.dkr.ecr.us-east-1.amazonaws.com/wetty-app:6c9d009-10"
      pullPolicy: "IfNotPresent"
    deploymentStrategy: "RollingUpdate"
    imagePullPolicy: "IfNotPresent"
    shcommand: "yarn start --sshhost wetty-ssh"

wettysshAdditionalVolumes:
  enabled: false
  pvcNames:
    - name: logs-vol
      mountPath: /var/log/efs
      claimName: logs-pvc