controllerManager:
  kubeRbacProxy:
    args:
    - --secure-listen-address=0.0.0.0:8443
    - --upstream=http://127.0.0.1:8080/
    - --logtostderr=true
    - --v=0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.13.1
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
  manager:
    service:
      port: 8081
      type: ClusterIP
    server:
      service:
        port: 9090
    logLevel: info
    args:
    - --health-probe-bind-address=:8081
    - --metrics-bind-address=127.0.0.1:8080
    - --leader-elect
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: vishnukvfacets/fc-uptime-monitor
      tag: 6
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
tolerations: []
nodeSelector: {}
metricsService:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: server
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP

frontend:
  enabled: true
  image:
    repository: vishnukvfacets/fc-uptime-monitor-ui
    tag: 11
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 80
  # Backend API endpoint configuration
  apiEndpoint: "/api"  # This will be constructed in the deployment template

enableCRDs: false
# History Provider Configuration
historyProvider:
  # Choose which provider to use: "prometheus", "victoriametrics", or leave empty for none
  type: "prometheus"
  
  # Prometheus configuration
  prometheus:
    endpoint: "http://prometheus-operator-prometheus.default.svc.cluster.local:9090"
  
  # VictoriaMetrics configuration
  victoriametrics:
    endpoint: "http://victoria-metrics-server.monitoring.svc.cluster.local"
