# Default values for deletePods.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: "bitnami/kubectl:1.16"
schedule: "0 0 * * *"
podStatusesToCleanUp: "NodeShutdown|Terminated"
filter: "Failed"
