{{- range .Values.cronConfig }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ .cronName }}
  labels:
    app: cronjob-{{ .cronName }}
    release: cronjob-{{ .cronName }}
    resource_type: "configuration"
    resource_name: "kubectl-crons"
spec:
  suspend: false
  concurrencyPolicy: Forbid
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: cronjob-{{ .cronName }}
            release: cronjob-{{ .cronName }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ $.Release.Name }}
          {{- with $.Values.tolerations }}
          tolerations:
            {{- . | toYaml | nindent 10 }}
          {{- end }}
          {{- with $.Values.nodeSelector }}
          nodeSelector:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          containers:
            - name: {{ $.Release.Name }}
              image: {{ $.Values.image | quote }}
              command: 
              - "sh"
              - "-c"
              - "{{ .command }}"
---
{{- end }}
