kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "facets-notification-cr"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "patch", "annotate"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets", "statefulsets", "cronjobs"]
  verbs: ["get", "list", "watch"]