apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "facets-notification-controller.fullname" . }}-mr
  labels:
  {{- include "facets-notification-controller.labels" . | nindent 4 }}
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "facets-notification-controller.fullname" . }}-mrb
  labels:
  {{- include "facets-notification-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "facets-notification-controller.fullname" . }}-mr'
subjects:
- kind: ServiceAccount
  name: '{{ include "facets-notification-controller.fullname" . }}'
  namespace: '{{ .Release.Namespace }}'
