{{- range $index, $commandConfig := .Values.commandConfig }}
{{- $status := "" -}}
{{- $namespaceArg := "" -}}
{{- $filterExpression := "" -}}
{{- if $commandConfig.status -}}
  {{- $status = printf "--field-selector=status.phase=%s" $commandConfig.status -}}  
{{ end }}
{{- if $commandConfig.namespace -}}
  {{- if eq $commandConfig.namespace "*" -}}
    {{- $namespaceArg = print "-A" -}}
  {{- else -}}
    {{- $namespaceArg = printf "-n=%s" $commandConfig.namespace -}}
  {{- end -}}
{{ end }}
{{- if $commandConfig.filter -}}
  {{- $filterExpression = printf "| grep -E %s" $commandConfig.filter -}}
{{ end }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $.Release.Name }}-{{ $commandConfig.name }}
  labels:
    app: cronjob-{{ $commandConfig.name }}
    release: cronjob-{{ $commandConfig.name }}
spec:
  suspend: false
  concurrencyPolicy: Forbid
  schedule: "{{ $.Values.schedule }}"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: cronjob-{{ $commandConfig.name }}
            release: cronjob-{{ $commandConfig.name }}
        spec:
          restartPolicy: Never
          serviceAccountName: {{ $.Release.Name }}
          containers:
            - name: {{ $.Release.Name }}
              image: "{{ $.Values.image }}"
              command: 
              - "sh"
              - "-c"
              - "{{ printf "%s %s %s %s" $commandConfig.command $status $namespaceArg $filterExpression }}"
{{- end }}
