apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ .Release.Name }}-fluentd
  name: {{ .Release.Name }}-fluentd
  namespace: default
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fluentd
      release: fluentd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fluentd
        name: {{ .Release.Name }}-fluentd
        release: fluentd
    spec:
      containers:
        - image: {{ .Values.fluentd.image.repository }}
          imagePullPolicy: {{ .Values.fluentd.imagePullPolicy }}
          name: {{ .Release.Name }}-fluentd
          env:
          - name: FLUENTD_ARGS
            value: "--no-supervisor -v"
          resources:
            limits:
              cpu: {{ .Values.fluentd.resources.limits.cpu }}
              memory: {{ .Values.fluentd.resources.limits.memory }}
          volumeMounts:
            - mountPath: /var/log/efs
              name: logs-vol
      priorityClassName: {{ .Values.fluentd.priorityClass.name }}
      restartPolicy: {{ .Values.fluentd.restartPolicy }}
      tolerations:
        - effect: {{ .Values.global.tolerations.effect }}
          key: {{ .Values.global.tolerations.key }}
          operator: {{ .Values.global.tolerations.operator }}
          value: {{ .Values.global.tolerations.value }}
      volumes:
        - name: logs-vol
          persistentVolumeClaim:
            claimName: {{ .Values.logsVolume.persistentVolumeClaims.name }}-pvc
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate

---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.logsVolume.persistentVolumeClaims.name }}-pvc
spec:
  accessModes:
    - {{ .Values.logsVolume.persistentVolumeClaims.accessMode }}
  storageClassName: {{ .Values.logsVolume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.logsVolume.persistentVolumeClaims.storageSize }}