## Storage class
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: {{ .Values.storageClassName }}
#mountOptions:
#  - file_mode=0777
#  - mfsymlinks
#  - gid=0
#  - uid=0
#  - dir_mode=0777
#  - actimeo=30
#  - cache=strict
#provisioner: kubernetes.io/azure-file
#allowVolumeExpansion: true
#reclaimPolicy: Retain
#volumeBindingMode: Immediate

---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaims.name }}-pvc
spec:
  accessModes:
    - {{ .Values.persistentVolumeClaims.accessMode }}
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaims.storageSize }}


