apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Release.Name }}-wetty-ssh
  name: {{ .Release.Name }}-wetty-ssh
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wetty-ssh
      release: wetty-ssh
  serviceName: wetty-ssh
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wetty-ssh
        release: wetty-ssh
    spec:
      containers:
        - image: {{ .Values.wettySsh.image }}
          imagePullPolicy: IfNotPresent
          name: {{ .Values.wettySsh.name }}
          ports:
          - containerPort: 22
            name: ssh
            protocol: TCP
          resources:
            limits:
              cpu: {{ .Values.wettySsh.resources.limits.cpu }}
              memory: {{ .Values.wettySsh.resources.limits.memory }}
          volumeMounts:
          - mountPath: /mnt/data
            name: data-vol
          - mountPath: /var/log/efs
            name: logs-vol-azure-files
            readOnly: true
          {{- if .Values.wettySsh.wettysshAdditionalVolumes.enabled }}
          {{- range .Values.wettySsh.wettysshAdditionalVolumes.pvcNames }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
            readOnly: true
          {{- end }}
          {{- end }}
      tolerations:
      - effect: {{ .Values.global.tolerations.effect }}
        key: {{ .Values.global.tolerations.key }}
        operator: {{ .Values.global.tolerations.operator }}
        value: {{ .Values.global.tolerations.value }}
      volumes:
      - name: logs-vol-azure-files
        persistentVolumeClaim:
          claimName: {{ .Values.logsVolume.persistentVolumeClaims.name }}-pvc
      {{- if .Values.wettySsh.wettysshAdditionalVolumes.enabled }}
      {{- range .Values.wettySsh.wettysshAdditionalVolumes.pvcNames }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .claimName }}
      {{- end }}
      {{- end }}
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

---
# Service wetty-ssh
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: {{ .Release.Name }}-wetty-ssh
    release: wetty-ssh
  name: wetty-ssh
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    app: {{ .Release.Name }}-wetty-ssh
    release: wetty-ssh
  type: ClusterIP

---
#For testing env when required secrets are not available
#apiVersion: v1
#kind: Secret
#metadata:
#  name: wetty-ssh-file-credentials
#  namespace: default
#type: Opaque

---
# Testing scenario in env where logs-pvc is available to have it mounted in wetty-ssh
# If present then validation as per wettysshAdditionalVolumes is associated
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: logs-pvc
#  namespace: default
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 5Gi
#  storageClassName: ccazfile




