apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.chartName }}-wetty
  name: {{ .Values.chartName }}-wetty
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.chartName }}-wetty
      release: wetty
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.chartName }}-wetty
        podSize: MICRO
        release: wetty
        resourceAllocationStrategy: GENERAL_PURPOSE
    spec:
      containers:
        - command:
            - sh
            - -c
            - {{ .Values.wetty.shcommand }}
          image: {{ .Values.wetty.image.repository }}
          imagePullPolicy: {{ .Values.wetty.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - -c
                  - sleep 30
          livenessProbe:
            failureThreshold: 20
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 10
          name: {{ .Values.wetty.name }}
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 20
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 125m
              memory: 512Mi
            requests:
              cpu: 125m
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/log/dumps
              name: dump-vol
            - mountPath: /etc/credentialfiles/
              name: wetty-file-credentials-vol
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot
      volumes:
        - hostPath:
            path: /var/log/dumps/wetty
            type: DirectoryOrCreate
          name: dump-vol
        - name: wetty-file-credentials-vol
          secret:
            defaultMode: 420
            secretName: wetty-file-credentials

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wetty
  name: wetty
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: wetty
    release: wetty
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: wetty-file-credentials
  namespace: default
type: Opaque