---
# This configmap contains all the scripts
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-audit-rest.hooks.fullname" . }}
  labels:
    {{- include "kube-audit-rest.labels" . | nindent 4 }}
  annotations:
    {{- include "kube-audit-rest.hooks.annotations" (dict "hooks" "pre-install,post-install,pre-upgrade,post-upgrade") | nindent 4 }}
data:
{{ (.Files.Glob "scripts/*").AsConfig | indent 2 }}  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-audit-rest.serviceAccountName" . }}
  labels: {{- include "kube-audit-rest.labels" . | nindent 4}}
  annotations:
    {{- include "kube-audit-rest.hooks.annotations" (dict "hooks" "pre-install,post-install,pre-upgrade,post-upgrade") | nindent 4 }}
{{- print "" }}
---
# Give read write access to the tls secret
{{ $roleName :=  include "kube-audit-rest.fullname" . | printf "%s-secret-rw" | trunc 63 -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}
  annotations:
    {{- include "kube-audit-rest.hooks.annotations" (dict "hooks" "pre-install,pre-upgrade") | nindent 4 }}
rules:
- apiGroups: [""]
  resourceNames: ["{{ include "kube-audit-rest.fullname" . }}"]
  resources: ["secrets"]
  verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleName }}
  annotations:
    {{- include "kube-audit-rest.hooks.annotations" (dict "hooks" "pre-install,pre-upgrade") | nindent 4 }}
subjects:
- kind: ServiceAccount
  name:  {{ include "kube-audit-rest.serviceAccountName" .}}
roleRef:
  kind: Role 
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
---