apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-audit-rest.fullname" . }}
  labels: {{ include "kube-audit-rest.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- if eq .Values.tls.mode "manual" }}
  {{- with .Values.tls.manual }}
    {{- . | toYaml | nindent 2 }}
  {{- end }}
  {{- else }}
  # These are placeholders which will be patched by the post install job
  tls.crt: "LS0tLS1CRUdJTiBQTEFDRUhPTERFUi0tLS0tCi0tLS0tRU5EIFBMQUNFSE9MREVSLS0tLS0="
  tls.key: "LS0tLS1CRUdJTiBQTEFDRUhPTERFUi0tLS0tCi0tLS0tRU5EIFBMQUNFSE9MREVSLS0tLS0="
  {{- end }}
