apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kube-audit-rest.fullname" . }}
  labels:
    {{- include "kube-audit-rest.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "kube-audit-rest.fullname" . -}} . {{- .Release.Namespace -}} .svc.cluster.local
    failurePolicy: Ignore # Don't block requests if auditing fails
    timeoutSeconds: 1 # To prevent excessively slowing everything
    sideEffects: None
    clientConfig:
      service:
        name: {{ include "kube-audit-rest.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/log-request"
      {{- if eq .Values.tls.mode "manual" }}
      caBundle: {{ index .Values.tls.manual "ca.crt" }}  
      {{- else }}
      caBundle: "LS0tLS1CRUdJTiBQTEFDRUhPTERFUi0tLS0tCi0tLS0tRU5EIFBMQUNFSE9MREVSLS0tLS0=" # To be replaced by post install job
      {{- end }}
    rules: # To be reduced as needed
      - operations: ["*"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*/*"]
        scope: "*" 
    admissionReviewVersions: ["v1"]
