---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: shell-operator
        image: "ghcr.io/flant/shell-operator:latest"
        imagePullPolicy: Always
        volumeMounts:
        - name: {{ .Release.Name }}
          mountPath: /hooks/
        {{- if (hasKey .Values "resources") }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      serviceAccountName: {{ .Release.Name }}
      {{- if (hasKey .Values "tolerations") }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
      {{- if (hasKey .Values "nodeSelector") }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 6 }}
      {{- end }}
      volumes:
      - name: {{ .Release.Name }}
        configMap:
          name: {{ .Release.Name }}
          defaultMode: 0777