apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app: compress-logs
  name: compress-logs
  namespace: default
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
    spec:
      template:
        metadata:
          annotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          labels:
            app: compress-logs
            release: compress-logs
        spec:
          containers:
            - env:
                - name: COMPRESS_LOGS_BEFORE_DAYS
                  valueFrom:
                    secretKeyRef:
                      key: COMPRESS_LOGS_BEFORE_DAYS
                      name: compress-logs-configs
              command:
                - /bin/sh
                - -c
                - find /var/log/efs -type f -name "*.log" -mtime +$COMPRESS_LOGS_BEFORE_DAYS
                  -exec sh -c 'pod=$(basename "${1%/*.*}"); day=$(date -r "$1" +%Y%m%d);
                  zip_file="${1%/*}/${pod}_${day}.zip"; [ -f "$zip_file" ] && cmd="zip
                  -j -u $zip_file $1" || cmd="zip -j $zip_file $1"; $cmd; rm "$1"' _ {}
                  \;
              image: facetscloud/alpine-zip:3.17.1
              imagePullPolicy: IfNotPresent
              name: compress-logs
              resources:
                limits:
                  cpu: 250m
                  memory: 1Gi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/credentialfiles/
                  name: compress-logs-file-credentials-vol
                - mountPath: /var/log/dumps
                  name: dump-vol
                - mountPath: /var/log/efs/
                  name: logs-vol-azure-files
          restartPolicy: Never
          tolerations:
            - effect: {{ .Values.global.tolerations.effect }}
              key: {{ .Values.global.tolerations.key }}
              operator: {{ .Values.global.tolerations.operator }}
              value: {{ .Values.global.tolerations.value }}
          volumes:
            - name: compress-logs-file-credentials-vol
              secret:
                defaultMode: 420
                secretName: compress-logs-file-credentials
            - hostPath:
                path: /var/log/dumps/compress-logs
                type: DirectoryOrCreate
              name: dump-vol
            - name: logs-vol-azure-files
              persistentVolumeClaim:
                claimName: {{ .Release.Name }}-pvc
  schedule: 00 17 * * *
  successfulJobsHistoryLimit: 3
  suspend: false

---
apiVersion: v1
kind: Secret
metadata:
  name: compress-logs-file-credentials
  namespace: default
type: Opaque
