apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: {{ .Release.Name }}-fluentd
  name: {{ .Release.Name }}-fluentd
  namespace: {{ .Values.fluentd.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-fluentd
      release: fluentd
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-fluentd
        name: {{ .Release.Name }}-fluentd
        release: fluentd
    spec:
      containers:
        - image: {{ .Values.fluentd.image.repository }}
          imagePullPolicy: {{ .Values.fluentd.imagePullPolicy }}
          name: {{ .Release.Name }}-fluentd
          env:
          - name: FLUENTD_ARGS
            value: "--no-supervisor -v"
          resources:
            limits:
              cpu: {{ .Values.fluentd.resources.limits.cpu }}
              memory: {{ .Values.fluentd.resources.limits.memory }}
          volumeMounts:
            - mountPath: /var/log/efs
              name: logs-vol-azure-files
      priorityClassName: {{ .Values.fluentd.priorityClass.name }}
      restartPolicy: {{ .Values.fluentd.restartPolicy }}
      tolerations:
        - effect: {{ .Values.global.tolerations.effect }}
          key: {{ .Values.global.tolerations.key }}
          operator: {{ .Values.global.tolerations.operator }}
          value: {{ .Values.global.tolerations.value }}
      volumes:
        - name: logs-vol-azure-files
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
  updateStrategy:
    rollingUpdate:
      maxSurge: {{ .Values.fluentd.updateStrategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.fluentd.updateStrategy.rollingUpdate.maxUnavailable }}
    type: {{ .Values.fluentd.updateStrategy.type }}

---
# PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ccazfile
  resources:
    requests:
      storage: {{ .Values.logsVolume.persistentVolumeClaim.storageSize }}