# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongodb-auth-operator
    app.kubernetes.io/part-of: mongodb-auth-operator
  {{- include "mongodb-auth-operator.labels" . | nindent 4 }}
  name: {{ include "mongodb-auth-operator.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mongodb-auth-operator
    app.kubernetes.io/part-of: mongodb-auth-operator
  {{- include "mongodb-auth-operator.labels" . | nindent 4 }}
  name: {{ include "mongodb-auth-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mongodb-auth-operator.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb-auth-operator.fullname" . }}-controller-manager
    namespace: {{ .Release.Namespace }}
