apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wireguard-operator.fullname" . }}-manager-role
  labels:
  {{- include "wireguard-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.example.com
  resources:
  - wireguardpeers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.example.com
  resources:
  - wireguardpeers/finalizers
  verbs:
  - update
- apiGroups:
  - vpn.example.com
  resources:
  - wireguardpeers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards/finalizers
  verbs:
  - update
- apiGroups:
  - vpn.example.com
  resources:
  - wireguards/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wireguard-operator.fullname" . }}-manager-rolebinding
  labels:
  {{- include "wireguard-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "wireguard-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "wireguard-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'